<?php

$youtube_videos_names["iTsRO21dS5k"] = "Hasta el 15 de Abril: VENUS RETRÓGRADO";
$youtube_videos_names["2m_5OMbD5aE"] = "Lo peor y lo mejor de los 12 Signos en el Amor";
$youtube_videos_names["TSUTs0PPmcg"] = "Cómo leer la Carta Natal";
$youtube_videos_names["gx1w7XUss4s"] = "AÑO NUEVO MUNDIAL 2017! Ingreso del Sol en ARIES";
$youtube_videos_names["8fNEnYiAyYk"] = "Eras Astrol&oacute;gicas";
$youtube_videos_names["A3tgK7XSLYc"] = "La Astrolog&iacute;a revela la Compatibilidad en el Amor";
$youtube_videos_names["G734iSl8Nf8"] = "PREDICCIONES ASTROLOG&Iacute;A 2016 A&Ntilde;O MUNDIAL";
$youtube_videos_names["nOEpcc1YS_M"] = "Astrolog&iacute;a";
$youtube_videos_names["ZN3dGb6-qtc"] = "Sue&ntilde;os Premonitorios, Astrolog&iacute;a y Sincronicidad";
$youtube_videos_names["dAzMbKaD6pI"] = "Precesi&oacute;n de los Equinoccios";
$youtube_videos_names["1GTmUTN9F58"] = "PROFEC&Iacute;AS DEL COMIENZO DEL NUEVO MILENIO";
$youtube_videos_names["03oePxDncgw"] = "Los miedos seg&uacute;n tu Signo del Zod&iacute;aco";
$youtube_videos_names["W5EoK0PW8iI"] = "Astrolog&iacute;a y la Era de Acuario";
$youtube_videos_names["6XAxoyU5na4"] = "Nuevo misterio: Detectan rayos X procedentes de Plut&oacute;n";
$youtube_videos_names["RDUkGxCY78U"] = "OFIUCO &iquest;El nuevo Signo del Zod&iacute;aco&quest;";
$youtube_videos_names["2kOOZot6WOk"] = "Astrolog&iacute;a, Karma y Transformaci&oacute;n";
$youtube_videos_names["k0gEKoGrUs4"] = "Tu profesi&oacute;n Ideal seg&uacute;n tu signo";
$youtube_videos_names["y_EWAP_OHZI"] = "Astrolog&iacute;a, la ciencia de las energ&iacute;as";
$youtube_videos_names["_og4jZPefbE"] = "La Otra Historia Oculta de la Humanidad";
$youtube_videos_names["dmza6GDFc6U"] = "El Saber de la Nueva Era";
$youtube_videos_names["rSg9x8PDAcI"] = "Plut&oacute;n, Capricornio y la Crisis Global";

$youtube_videos_descriptions["iTsRO21dS5k"] = "Durante 40 días Venus retrocede en el Signo de Aries. Venus normalmente nos impulsa a buscar la belleza, el amor y la comodidad en el mundo externo. Nos incita a aprender y a valorar a otros seres, y nos sensibiliza ante el potencial estético de la vida. Los planetas retrógrados simbolizan el retorno de la líbido (la energía psíquica o la fuerza vital) del consciente dentro del inconsciente. ¿Cómo operará esta influencia en todos nosotros?";
$youtube_videos_descriptions["2m_5OMbD5aE"] = "Cada uno de los 12 Signos tiene su costado luminoso, y un aspecto oscuro en el amor. Conocer ambos puede ayudarte a descifrar la personalidad de tu pareja y conocerte más a vos mism@.
<br />Todas las personas tenemos rasgos positivos y negativos. El psiquiatra suizo Carl Jung fue el primero en hablar sobre ese costado de la personalidad, al que llamó la Sombra, el lado oscuro.
<br />No siempre es agradable conocer ese espacio que solemos esconder… pero conocerlo permite ";
$youtube_videos_descriptions["TSUTs0PPmcg"] = "La Carta Natal es el mejor Test de nuestra personalidad. Nos sirve a modo de GPS, para orientarnos hacia en nuestra personalidad esencial. 
Te dejamos las 4 Claves para que aprendas a leer el lenguaje de la astrología.";
$youtube_videos_descriptions["gx1w7XUss4s"] = "El Nuevo Año astrológico no empezó el 1º de enero sino el 20 de marzo. Eso significa que a nivel energético las influencias que se marcan ése día son las que funcionarán durante todo el año 2017. 
<br />La fecha está determinada por el Equinoccio Vernal, ingreso del Sol en el punto Vernal ó 0° de Aries, lo cual indica también el inicio del Otoño en el Hemisferio Sur (y Primavera para el Norte)
<br />Este año 2017 el equinoccio de otoño se produjo el 20 de marzo a las 10h28m AM Hora de Greenwich.
Un ciclo se muere, otro inicia. Todo es cíclico en la Naturaleza. 
En ese momento los Astrólogos calculan una carta que indica las influencias sociales, políticas, económicas, que habrá a nivel mundial cada año. 
El conocer las influencias del inicio del año permite estar preparado para lo bueno así como para lo malo, permite ubicarnos a los seres humanos dentro de esta gran sinfonía cósmica, y evitamos mantenernos en la ignorancia acerca de las fuerzas de la naturaleza y del cosmos.";
$youtube_videos_descriptions["8fNEnYiAyYk"] = "Estamos en un momento muy importante como humanidad con grandes cambios a nivel climático, social, económico y psicológico. Todas las culturas antiguas desde hace más de 2000 años nos dejaron enseñanzas acerca de este momento especial en la forma de profecías. Estos cambios no se dan de forma casual sino de acuerdo a lo que en la Astrología se llaman Eras Astrológicas. Comenzamos aquí introduciendo este apasionante tema.";
$youtube_videos_descriptions["A3tgK7XSLYc"] = "";
$youtube_videos_descriptions["G734iSl8Nf8"] = "¿Es el fin el mundo este año? - Aprendé las principales influencias astrológicas para el año 2016 y preparate para poder trabajar con ellas de un modo consciente.";
$youtube_videos_descriptions["nOEpcc1YS_M"] = "CURSO DE ASTROLOGÍA<br />Anotate ahora y obtené importantes descuento y la matrícula bonificada.";
$youtube_videos_descriptions["ZN3dGb6-qtc"] = "¿Alguna vez tuviste un sueño premonitorio que te anticipe el futuro? En este video la Dra. Von Franz nos cuenta la relación entre este tipo de sueños y la Ley de Sincronicidad.<br /><br />Si bien estos sueños son más frecuentes de lo que habitualmente se cree, los enfoques materialistas desechan éstos fenómenos ya que no pueden explicarlos.<br /><br />Sin embargo la Psicología de Jung explica por qué se producen estos sueños que nos muestran el futuro, sea como aviso, advertencia o guía, y que son inexplicables desde el punto de vista de la Causa-Efecto.<br /><br />Jung denominó Sincronicidad a la Ley A- Causal que explica lo que se suelen llamar equivocadamente “casualidades”. La Ley de Sincronicidad demuestra la relación entre la mente (nuestro mundo interior ) y el mundo externo.<br /><br />¿Conocías a Maria Luisa von Franz? Fue una de las principales discípulas de Carl Jung. Dedicó su vida al análisis de sueños, e investigó la Alquimia y la Sincronicidad.";
$youtube_videos_descriptions["dAzMbKaD6pI"] = 'Fragmento del Documental "La Astrología y la Era de Acuario".<br /><br />Es necesario en estos momentos que la HUMANIDAD inicia una NUEVA ERA, que la Astrología, la Ciencia y la Psicología, y lo que atañe a lo espiritual en el hombre, trabajen juntas, que formulen un compromiso de buscar la verdad y el conocimiento total integrador, que el mero análisis de recoger y analizar hechos aislados.<br /><br />Prof. Florencia Santoni<br />Astróloga';
$youtube_videos_descriptions["1GTmUTN9F58"] = "A lo largo de la historia las profecías se convirtieron en importantes evidencias de un saber milenario y misterioso. Demostraron que existen otro tipo de causas y desencadenantes en los eventos mundiales. Hoy nos toca afrontar las crisis modernas (políticas, sociales, económicas, climáticas, etc, y el desafío estará en la capacidad de tomar consciencia o no como individuos, para proseguir con la evolución de la humanidad o en su defecto, conducirnos a la inevitable autodestrucción.";
$youtube_videos_descriptions["03oePxDncgw"] = "Detectar y reconocer aquello que nos causa temor o inseguridad es el primer paso para poder superarlo. Cada uno de los 12 Signos del zodíaco, según su propia naturaleza, experimenta la tendencia a sentir temor a una u otra cosa.<br />Ante todo es fundamental saber que hay un tipo de miedo que es instintivo, que nos alerta y preserva frente al peligro. Pero la mayoría de los temores que padecemos son de naturaleza emocional y se basan en fantasías, proyecciones, falta de conocimiento o formas equivocadas de pensar. Es sobre este tipo de emoción negativa de la cual debemos liberarnos.<br />Conocé tus miedos según tu signo y comienza a liberarte de ellos.";
$youtube_videos_descriptions["W5EoK0PW8iI"] = "Es necesario en estos momentos que la HUMANIDAD inicia una NUEVA ERA, que la Astrología, la Ciencia y la Psicología, y lo que atañe a lo espiritual en el hombre, trabajen juntas, que formulen un compromiso de buscar la verdad y el conocimiento total integrador, que el mero análisis de recoger y analizar hechos aislados.<br /><br />Prof. Florencia Santoni<br />Astróloga";
$youtube_videos_descriptions["6XAxoyU5na4"] = "La Nasa ha descubierto un misterioso fenómeno en Plutón. El planeta por sus condiciones no debería estar emitiendo Rayos X. Descubrí que tiene para decir la Astrología al respecto.";
$youtube_videos_descriptions["RDUkGxCY78U"] = "Una noticia reciente de la NASA asegura que habría descubierto el treceavo Signo del Zodíaco, Ofiuco ¿Es esto cierto? ¿Qué diferencia hay entre Signos y Constelaciones? Se ha abierto una nueva polémica ¿qué pensás al respecto?";
$youtube_videos_descriptions["2kOOZot6WOk"] = "Nacemos en un momento único relacionado a nuestro Karma del pasado. Ya sea que identifiquemos cualidades positivas (Karma Positivo) como talentos o cualidades negativas (Karma Negativo), en cualquiera de los dos casos la transformación se hace necesaria ya que estas cualidades se expresan en un nuevo cuerpo y en un nuevo momento de la historia con sus particularidades.";
$youtube_videos_descriptions["k0gEKoGrUs4"] = "Elegir la carrera profesional y descubrir nuestra verdadera vocación, muchas veces no es tan fácil. La Astrología a través de la carta natal, permite obtener una certera Orientación Vocacional según nuestras capacidades e intereses. Una carta natal puede ofrecer una comprensión valiosa acerca de las habilidades, dificultades y potenciales individuales específicos, con relación al tema de la vocación.<br />En este video encontrarás una guía de la Profesión ideal según cada signo del zodíaco.";
$youtube_videos_descriptions["y_EWAP_OHZI"] = "La Astrología se define como el estudio de las influencias cósmicas que recibimos constantemente. Numerosas comprobaciones tales como que la luna regula el movimiento de las mareas y los ciclos biológicos de plantas y animales, o que el ciclo de manchas solares afecta el clima y las telecomunicaciones, entre tantas otras, sustentan esta milenaria ciencia y arte. Los seres humanos también somos afectados por estos ciclos planetarios. La carta natal lo comprueba.<br /><br />Sin embargo, hoy en día algunos siguen remitiendo la Astrología a los horóscopos de los diarios y revistas, a una mancia y por lo tanto superstición.<br /><br />No obstante, destacados científicos y pensadores de todas las épocas practicaron y utilizaron la Astrología como una guía personal para el presente y el futuro ¿es posible que estuvieran todos ellos equivocados?<br /><br />La Astrología no es de ningún modo algo en lo que debamos CREER sino que es un SABER al que podemos acceder, y comprobar por nosotros mismos para sacar nuestras propias conclusiones de esta maravillosa herramienta.<br /><br />¿Querés saber más?";
$youtube_videos_descriptions["_og4jZPefbE"] = "En este video veremos una descripción completamente diferente de nuestro pasado histórico.<br /><br />Algunos de los temas abordados son los siguientes:<br />- La importancia de la Historia<br />- Somos Seres Históricos<br />- La Historia de la humanidad y nuestra historia individual se entretejen<br />- El Revisionismo histórico y la Evolución Planetaria y de la Consciencia<br />- Descripción de los distintos tipos de cultura para explicar el origen de nuestra descripción histórica.<br />- Descripción del trabajo esotérico de investigación que ha hecho nuestra Escuela.";
$youtube_videos_descriptions["dmza6GDFc6U"] = "¿Por qué no puedes hacer tu verdadero destino?<br />¿Por qué en la Sociedad vemos que una y otra vez todo se repite mecánicamente?<br />¿Tienes verdaderas herramientas para conocerte y saber si estás actuando correctamente?<br /><br />Estas son algunas de las preguntas que todos debiéramos hacernos alguna vez. Sin embargo la vida acelerada y frenética de hoy hace que reprimamos este impulso o que simplemente nos posterguemos, anteponiendo siempre otros intereses u obligaciones.<br /><br />En este video el Prof. León Azulay nos da algunas respuestas y conocimientos imprescindibles para nuestro desarrollo personal.";
$youtube_videos_descriptions["rSg9x8PDAcI"] = "¿Hay otro tipo de causas y desencadenantes de los eventos mundiales que lo que nos dicen los medios masivos de comunicación?
Respecto a la Crisis del 2008 se han hecho películas y programas de tv, desarrollando posibles causas políticas, sociales y económicas. Sin embargo, la crisis actual es profunda y no se limita nada más a un tema económico.<br /><br />En este video la Prof. Florencia Santoni explica que hay fuerzas que movilizan y gatillan procesos personales y globales, la Astrologia Mundial se dedica a la investigación y comprobación de estos fenómenos.";

?>